### PR TITLE
Update module version and regenerate client

### PR DESCRIPTION
**Pull request by hallabro**
Before we create a new release we need to fix the module path. As part of updating the path to `v2` we also need to regenerate the client.

### CODE REVIEW

**Review by wojciecholszewski-form3 — APPROVED** [review]
LGTM

**Comment by hallabro** [comment]
Versions prior to go-swagger v0.22 (we were using v0.19) had no support for go modules and did not as such generate the proper module paths with the `v2` included.

In this migration a few changes had to be made in the templates but they were seemingly small.

For reference some of the changes are described in the commit `b99967394036105c3d6cbbfd604b13645f651ca2` of go-swagger.

In addition the package `form3_test` was merged into `form3`.

**Comment by hallabro** [comment]
It also contains a breaking change (`NewTokenBasedHttpClient` becomes `NewTokenBasedHTTPClient` and other small changes) but seeing as this is the first working (?) release of `v2` I think this would be acceptable.

We could potentially release it as `2.1` if we want to be sure the changes are noticed.

**Comment by wojciecholszewski-form3** [comment]
> We could potentially release it as `2.1` if we want to be sure the changes are noticed.

👍  for `v2.1.0`

**Review by wojciecholszewski-form3 — APPROVED** [review]

**Pull request merged**
